#Initialization
import turtle
IVT = turtle.Turtle()
nora = turtle.Turtle()
IVT.speed(10)
nora.speed(10)
#Functions
def catHead():
    IVT.goto(0,0)
    IVT.circle(125,360)
def catBody():
    IVT.penup()
    IVT.goto(35,50)
    IVT.right(30)
    IVT.pendown()
    IVT.left(225)
    IVT.circle(175,90)
    IVT.circle(100,90)
    IVT.circle(175,90)
    IVT.circle(100,90)
def catLeg():
    IVT.right(25)
    IVT.circle(100,70)
    IVT.circle(20,110)
    IVT.circle(100,70)
    IVT.circle(19,110)
def catFoot():
    IVT.circle(15,110)
    IVT.circle(75,70)
    IVT.circle(14,110)
    IVT.circle(75,70)

def EarsandTail():
    nora.penup()
    nora.forward(175)
    nora.right(90)
    nora.forward(175)
    nora.left(90)
    nora.pendown()
    #TAIL
    nora.pensize(25)
    nora.circle(125, 90)
    nora.forward(50)
    nora.left(90)
    nora.forward(20)
    nora.penup()
    nora.forward(100)
    nora.left(90)
    nora.forward(150)
    nora.left(90)
    nora.pendown()
    nora.circle(100, 90)
    nora.forward(50)
    #TRANSITION
    nora.penup()
    nora.forward(200)
    nora.left(90)
    nora.forward(175)
    nora.right(90)
    #EARS
    nora.pensize(60)
    nora.pendown()
    nora.left(5)
    nora.forward(50)
    nora.circle(5, 135)
    nora.forward(50)
    #TRANSITION #2
    nora.penup()
    nora.right(50)
    nora.forward(120)
    #EARS #2
    nora.pendown()
    nora.right(45)
    nora.forward(50)
    nora.circle(5, 135)
    nora.forward(50)

def drawEyes():
    #TRANSITION #3
    nora.pensize(1)
    nora.penup()
    nora.forward(65)
    nora.left(90)
    nora.forward(60)
    nora.pendown()
    #EYES #1
    nora.fillcolor("yellow")
    nora.begin_fill()
    nora.circle(8,180)
    nora.forward(30)
    nora.circle(8,180)
    nora.forward(30)
    nora.end_fill()
    nora.left(150)
    nora.forward(15)
    nora.dot(20)
    #TRANSITION #4
    nora.penup()
    nora.right(150)
    nora.forward(105)
    nora.pendown()
    #EYES #2
    nora.begin_fill()
    nora.right(90)
    nora.forward(8)
    nora.left(90)
    nora.circle(8,180)
    nora.forward(30)
    nora.circle(8,180)
    nora.forward(30)
    nora.end_fill()
    nora.left(150)
    nora.forward(15)
    nora.dot(20)

def drawface():
    #TRANSITION #5
    nora.penup()
    nora.forward(80)
    nora.left(95)
    nora.forward(80)
    nora.right(75)
    #WHISKERS #1
    nora.pencolor("white")
    nora.pendown()
    nora.forward(45)
    nora.backward(45)
    nora.penup()
    nora.left(90)
    nora.forward(5)
    nora.right(90)
    nora.pendown()
    nora.forward(55)
    nora.backward(55)
    nora.penup()
    nora.left(105)
    nora.forward(5)
    nora.right(100)
    nora.pendown()
    nora.forward(45)
    nora.backward(45)
    #TRANSITION #6
    nora.penup()
    nora.right(175)
    nora.forward(150)
    nora.left(90)
    nora.forward(5)
    nora.right(90)
    #WHISKERS #2
    nora.pendown()
    nora.left(15)
    nora.forward(45)
    nora.backward(45)
    nora.right(105)
    nora.penup()
    nora.forward(5)
    nora.pendown()
    nora.left(80)
    nora.forward(55)
    nora.backward(55)
    nora.right(90)
    nora.penup()
    nora.forward(5)
    nora.pendown()
    nora.left(75)
    nora.forward(45)
    nora.backward(45)
    #TRANSITION #7, NOSE + FACE
    nora.right(160)
    nora.penup()
    nora.forward(75)
    nora.right(90)
    nora.color("gray")
    nora.begin_fill()
    nora.pendown()
    nora.circle(25,85)
    nora.left(25)
    nora.circle(25, 85)
    nora.left(70)
    nora.circle(100, 25)
    nora.end_fill()
    nora.penup()
    nora.backward(20)
    nora.right(103)
    nora.pendown()
    nora.forward(25)
    nora.left(90)
    nora.circle(50, 35)
    nora.left(155)
    nora.penup()
    nora.forward(30)
    nora.left(90)
    nora.forward(5)
    nora.right(300)
    nora.backward(35)
    nora.right(90)
    nora.forward(5)
    nora.left(90)
    nora.pendown()
    nora.circle(50,45)

def drawCat():
    IVT.speed(10)
    IVT.fillcolor("black")
    IVT.begin_fill()
    catHead()
    IVT.end_fill()
    
    IVT.penup() #back left paw
    IVT.goto(50,-230)
    IVT.pendown()
    IVT.left(30)
    catFoot()
    
    IVT.begin_fill() #torso
    catBody()
    IVT.end_fill()

    IVT.fillcolor("white")
    IVT.begin_fill()
    IVT.penup()
    IVT.goto(150,-220)
    IVT.pendown() #back right paw
    catFoot()
    IVT.end_fill()
    
    IVT.penup() #back right leg
    IVT.goto(175,-100)
    IVT.pendown()
    IVT.left(35)
    IVT.fillcolor("black")
    IVT.begin_fill()
    catLeg()
    IVT.end_fill()
    
    IVT.penup() #front left leg
    IVT.goto(10,-120)
    IVT.pendown()
    IVT.begin_fill()
    catLeg()
    IVT.end_fill()
    
    IVT.penup() # front right leg
    IVT.goto(120,-130)
    IVT.pendown()
    IVT.left(60)
    IVT.begin_fill()
    catLeg()
    IVT.end_fill()

    IVT.fillcolor("white")
    IVT.begin_fill()
    IVT.penup()#front right paw
    IVT.goto(115,-230)
    IVT.pendown()
    IVT.right(30)
    catFoot()
    IVT.end_fill()

    IVT.begin_fill()
    IVT.penup()#front left paw
    IVT.goto(-55,-230)
    IVT.pendown()
    IVT.right(0)
    catFoot()
    IVT.end_fill()

    IVT.fillcolor("black")
    IVT.begin_fill() #torso again
    IVT.right(180)
    catBody()
    IVT.end_fill()

    EarsandTail()
    drawEyes()
    drawface()
    
#Main
drawCat()
