#Group Members Ivan Tan, Nora Rogozinski, Nathan Garino, Renzo Sansonetti
#Date 7/1
#Initialization
import turtle
import random
turtle.colormode(255)
IVT=turtle.Turtle()
IVT.speed(0)
nora = turtle.Turtle()
nora.speed(0)
Renzo = turtle.Turtle()
Renzo.speed(0)
Nathan = turtle.Turtle()
Nathan.speed(0)
#Functions
def backround(): #creates a night sky with randomized stars - Renzo
    Renzo.backward(300)
    Renzo.dot(1000000, "darkblue")
    Renzo.dot(1000, "blue")
    Renzo.dot(700, "#0487DE")
    for i in range(100):
        sizerand=random.randint(5,10)
        locorand1=random.randint(-500,500)
        locorand2=random.randint(150,400)
        Renzo.penup()
        Renzo.goto(locorand1, locorand2)
        Renzo.pendown()
        color=random.randint(1,2)
        if color == 1:
            Renzo.dot(sizerand, 'white')
        if color==2:
            Renzo.dot(sizerand,'yellow')
def fireworkShow(): # spams fireworks 1 and 2 repeatedly - Nathan
    Nathan.left(90)
    for i in range(20):
        xloc = random.randint(-400,100)
        choice = random.randint(1,2)
        Nathan.penup()
        Nathan.goto(xloc,0)
        Nathan.pendown()
        if choice == 1:
            firework()
        if choice == 2:
            firework2()
def firework2(): #makes a firework that shoots off to the right - Nathan
    Nathan.width(5)
    amountOfSpokes = random.randint(10,15)
    spokes = random.randint(80,120)
    fireworkArc = random.randint(300,500)
    fireworkArcLength = random.randint(30,40)
    red = random.randint(0,255)
    green = random.randint(0,255)
    blue = random.randint(0,255)
    Nathan.color(red,green,blue)
    Nathan.circle(-fireworkArc,fireworkArcLength)
    Nathan.left(fireworkArcLength)
    Nathan.width(3)
    for i in range(amountOfSpokes):
        Nathan.right(360/amountOfSpokes)
        Nathan.circle(spokes,30)
        Nathan.circle(spokes,-30)
def firework(): #makes a firework that shoots off to the left - Nathan
    spokes = random.randint(80,120)
    Nathan.width(5)
    amountOfSpokes = random.randint(10,15)
    fireworkArc = random.randint(300,500)
    fireworkArcLength = random.randint(30,40)
    red = random.randint(0,255)
    green = random.randint(0,255)
    blue = random.randint(0,255)
    Nathan.color(red,green,blue)
    Nathan.circle(fireworkArc,fireworkArcLength)
    Nathan.right(fireworkArcLength)
    Nathan.width(3)
    for i in range(amountOfSpokes):
        Nathan.right(360/amountOfSpokes)
        Nathan.circle(spokes,30)
        Nathan.circle(spokes,-30)
def cliff(red, green, blue): #makes a rocky cliff - Nora
    nora.penup()
    nora.left(180)
    nora.forward(480)
    nora.right(90)
    nora.forward(200)
    nora.right(90)
    nora.pendown()
    nora.color(red, green, blue)
    nora.begin_fill()
    nora.forward(40)
    for i in range(5):
        nora.right(45)
        nora.forward(10)
        nora.right(20)
        nora.forward(25)
        nora.left(15)
        nora.forward(15)
        nora.left(55)
    nora.right(95)
    nora.forward(100)
    nora.left(55)
    for i in range(5):
        nora.right(45)
        nora.forward(10)
        nora.right(20)
        nora.forward(25)
        nora.left(15)
        nora.forward(15)
        nora.left(55)
    nora.forward(50)
    for i in range(3):
        nora.right(45)
        nora.forward(10)
        nora.right(20)
        nora.forward(25)
        nora.left(15)
        nora.forward(15)
        nora.left(55)
    nora.right(115)
    nora.forward(20)
    nora.right(90)
    nora.forward(520)
    nora.right(90)
    nora.forward(600)
    nora.end_fill()
def house(): #makes the entire house, including all of the windows, the door and the roof -Nora
    nora.penup()
    nora.color((random.randint(200, 255)), (random.randint(0,85)), (random.randint(0, 85)))
    nora.right(90)
    nora.forward(75)
    nora.right(90)
    nora.forward(200)
    nora.pendown
    nora.begin_fill()
    #base
    for i in range(4):
        nora.forward(125)
        nora.right(90)
    nora.end_fill()
    nora.color((random.randint(200, 255)), (random.randint(200,255)), (random.randint(200, 255)))
    nora.begin_fill()
    nora.right(150)
    #roof of house - Nora
    for i in range(3):
        nora.forward(135)
        nora.left(120)
    nora.end_fill()
    nora.left(60)
    nora.left(90)
    nora.penup()
    nora.forward(45)
    nora.right(90)
    nora.forward(15)
    nora.pendown()
    nora.color("yellow")
    nora.begin_fill()
    #right window of house - Nora
    for i in range(4):
        nora.forward(40)
        nora.right(90)
    nora.end_fill()
    nora.penup()
    nora.forward(55)
    nora.pendown()
    nora.begin_fill()
    #left window of house - Nora
    for i in range(4):
        nora.forward(40)
        nora.right(90)
    #door of house - Nora
    nora.end_fill()
    nora.right(180)
    nora.penup()
    nora.forward(20)
    nora.forward(10)
    nora.right(90)
    nora.forward(20)
    nora.pendown()
    nora.begin_fill()
    nora.forward(60)
    nora.right(90)
    nora.forward(40)
    nora.right(90)
    nora.forward(60)
    nora.right(90)
    nora.forward(40)
    nora.end_fill()
def randomGuy(): #makes a guy - Nora
    nora.penup()
    nora.forward(100)
    nora.pendown()
    nora.color("black")
    nora.pensize(5)
    nora.circle(15,360)
    nora.right(90)
    nora.forward(45)
    nora.left(60)
    nora.forward(25)
    nora.backward(25)
    nora.right(120)
    nora.forward(25)
    nora.backward(25)
    nora.right(125)
    nora.forward(25)
    nora.right(60)
    nora.forward(25)
    nora.backward(25)
    nora.left(120)
    nora.forward(25)
def ocean(wave,frequency,size): #creates blue squiggly lines that are layered - Ivan
    IVT.pensize(size)
    IVT.penup()
    IVT.goto(0,0)
    IVT.pendown()
    IVT.right(90)
    for i in range(45):
        randblu=random.randint(75,255)
        randgrn=random.randint(0,50)
        IVT.pencolor((0,randgrn,randblu))
        for i in range(13):
            IVT.circle(wave,180)
            IVT.forward(frequency)
            IVT.right(180)
            IVT.circle(wave,-180)
            IVT.right(180)
            IVT.forward(frequency)
        IVT.penup() #shifts waves down one row
        IVT.right(90)
        IVT.forward(520)
        IVT.left(90)
        IVT.pendown()
        IVT.forward(size)
def cityFoundation(): #makes ground for buildings to sit on - Ivan
    IVT.goto(0,25)
    IVT.left(90)#change to 0 if testing this function only change to 90 in final
    IVT.color("black")
    IVT.pensize(1)
    IVT.begin_fill()
    IVT.forward(225)
    IVT.right(80)
    IVT.forward(500)
    IVT.right(100)
    IVT.forward(900)
    IVT.right(90)
    IVT.forward(493)
    IVT.right(90)
    IVT.forward(575)
    IVT.end_fill()
def cityBuildings(): #makes buildings that appear randomly - Ivan
    IVT.penup()
    IVT.goto(175,0)
    IVT.pendown()
    IVT.right(180)
    for i in range(20):
        for i in range(20):
            randwidth=random.randint(20,40)
            randlength=random.randint(25,100)
            IVT.fillcolor("gray")
            IVT.begin_fill()
            IVT.forward(randwidth)
            IVT.right(90)
            IVT.forward(randlength)
            IVT.right(90)
            IVT.forward(randwidth)
            IVT.right(90)
            IVT.forward(randlength)
            IVT.right(90)
            IVT.end_fill()
            IVT.forward(randwidth+10)
        IVT.penup() #shifts buildings down one row
        IVT.right(180)
        IVT.forward(805)
        IVT.right(90)
        IVT.forward(25)
        IVT.right(90)
        IVT.pendown()
#Main
backround()
ocean(10,1,10)
cityFoundation()
cityBuildings()
fireworkShow()
cliff(106,106,106)
house()
randomGuy()
